{
  "type": "record",
  "name": "CompteEditeur",
  "namespace": "com.example.events",
  "fields": [
    { "name": "idEditeur", "type": "long" },
    { "name": "nom", "type": "string" },
    { "name": "prenom", "type": "string" },
    { "name": "email", "type": "string" },
    { "name": "pseudo", "type": "string" },
    { "name": "motDePasse", "type": "string" },
    { "name": "DateDeNaissance", "type": "string" },
    { "name": "DateDeCreationDuCompte", 
      "type": { "type": "long", "logicalType": "timestamp-millis" } 
    }
  ]
}


