{
    "type":"record",
    "name":"PublicationDLC",
    "namespace": "com.example.events",
    "doc" : "Évènement émis lorsqu'un DLC est publié par l'éditeur",
    "fields":
    [
        {
            "name": "id", 
            "type": "long"
        },
        
        {
            "name": "nom", 
            "type": "string"
        },

        {
            "name": "versionActuelle", 
            "type": "string",
            "doc" : "Version du jeu sur lequel on apporte une extension"
        },

        {
            "name": "genre", 
            "type": "string"
        },

        {
            "name": "prixEditeur", 
            "type": "int",
            "doc" : "prix fixé par l'éditeur à l'initial"
        },

        {
            "name": "type", 
            "type": "string"
        },

        {
            "name": "idEditeur", 
            "type": "long"
        },

        {
            "name": "idParent", 
            "type": "long",
            "doc" : "id du jeu auquel l'extension est rajoutée"
        }

    ]
}