{
  "type": "record",
  "name": "ReponseListeEvaluations",
  "namespace": "com.example.events",
  "fields": [
    { "name": "idJeu", "type": "long" },
    {
      "name": "evaluations",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "InfoEvaluation",
          "fields": [
            { "name": "idEvaluation", "type": "long"},
            { "name": "Note", "type": "int" },
            { "name": "versionJeu", "type": "string" },
            { "name": "Commentaire", "type": ["null", "string"], "default": null },
            { "name": "DateEvaluationJeu", "type": { "type": "long", "logicalType": "timestamp-millis" } }
          ]
        }
      }
    }
  ]
}