# Niveau par défaut : On ne veut voir que les erreurs graves
org.slf4j.simpleLogger.defaultLogLevel=warn

# On veut quand même voir TES messages (System.out) ou tes propres logs
org.slf4j.simpleLogger.log.com.projet_JVM2_DATA=info

# On fait taire les bavards spécifiques
org.slf4j.simpleLogger.log.org.apache.kafka=warn
org.slf4j.simpleLogger.log.io.confluent=warn
org.slf4j.simpleLogger.log.org.hibernate=warn
org.slf4j.simpleLogger.log.org.apache.zookeeper=warn